Timer UI
BeyondTheEcho/Capstone_Project pull request #70
Opened 2023-04-02 01:45 UTC by LiChung-Hao

Timer in minutes
Menu UI
Credit Scene
Time up scene

2023-04-02 18:52 UTC, JoshuaDaSilva commented on Assets/Scripts/Content.cs
> +    private string[] m_lines = new string[LINESNUM];
Just remember in any place with m_ or s_ the next word needs to be capital so in this case m_Lines

2023-04-02 18:58 UTC, JoshuaDaSilva requested changes
Overall, great work Li. I'd also change the timer to at least a minute because it is only at 2 seconds right now. I'm sure it was just for testing purposes but I would still change it prior to merging so that we don't have to worry about changing it in another branch.
Keep up to great work Li.

2023-04-02 18:58 UTC, JoshuaDaSilva commented on Assets/Scripts/Content.cs
> +        if (Input.GetMouseButtonDown(0))
You'll need to add Input.GetButtonDown("Add1") back into the if statement for the controller to work

2023-04-02 18:58 UTC, JoshuaDaSilva commented on Assets/Scripts/Content.cs
> +        if (m_conversationOver || Input.GetKeyDown(KeyCode.Escape))
Same thing here. Needs to be added back

2023-04-02 18:58 UTC, JoshuaDaSilva commented on Assets/Scripts/Content.cs
> +        if (m_conversationOver || Input.GetKeyDown(KeyCode.Escape))
m_ConversationOver

2023-04-02 18:58 UTC, JoshuaDaSilva commented on Assets/Scripts/Content.cs
> +            if (i != m_talkerIndex || m_textComponent.text == m_lines[m_index])
m_TalkerIndex, m_Index

2023-04-02 18:58 UTC, JoshuaDaSilva commented on Assets/Scripts/Content.cs
> +        StartTalking(m_storyTellerMouth[m_talkerIndex]);
m_StoryTeller, m_StoryTellerMouth

2023-04-03 19:24 UTC, JoshuaDaSilva approved these changes
Great work Li. The changes to the timing will help the game going forward

2023-04-03 19:54 UTC, Dunwaru commented on Assets/Sprites/Credit/snowedinlogo.png
Dom we have permission of this?

2023-04-03 19:55 UTC, Dunwaru commented on Assets/Sprites/SceneBG/BG1-MENU.png
I like this image

2023-04-03 19:58 UTC, LiChung-Hao commented on Assets/Sprites/Credit/Ethan.png
Sure

2023-04-03 19:59 UTC, LiChung-Hao commented on Assets/Sprites/Credit/snowedinlogo.png
remove it first, wait for Johanne's (SnowedIn HR)feedback

2023-04-03 20:20 UTC, Dunwaru approved these changes

2023-04-03 20:21 UTC, merged