Credit story
BeyondTheEcho/Capstone_Project pull request #91
Opened 2023-04-18 14:41 UTC by LiChung-Hao

Timer in text, menu language to button, timeup scene language value drag back

2023-04-18 20:31 UTC, JoshuaDaSilva requested changes
Everything looks great Li. My only minor thing would be the spacing for the timer.
![Screenshot 2023-04-18 163046](https://user-images.githubusercontent.com/91571514/232898051-c35c19e0-afce-4797-a485-ffb2aba39679.png)
If you can bring the number on the left a little bit more in

2023-04-20 13:37 UTC, LiChung-Hao commented
> Everything looks great Li. My only minor thing would be the spacing for the timer. ![Screenshot 2023-04-18 163046]If you can bring the number on the left a little bit more in.
![image](https://user-images.githubusercontent.com/91105935/233383592-c4547e1f-3541-4bfc-bdb4-61d14959c110.png)

2023-04-20 13:47 UTC, JoshuaDaSilva approved these changes
Great work Li. Thanks for making the changes

2023-04-20 13:59 UTC, Dunwaru approved these changes

2023-04-20 13:59 UTC, merged